apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: logging
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway
        isDefault: false
        editable: true
        jsonData:
          maxLines: 1000
