{{- if gt (int .Values.read.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.readFullname" . }}
  labels:
    {{- include "loki.readLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.readSelectorLabels" . | nindent 6 }}
  maxUnavailable: 1
{{- end }}
