# ApisixRoute-nexus-v1.yaml
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: nexus
  namespace: default
spec:
  http:
    - name: root
      match:
        hosts:
          - ops.qikqiak.com
        paths:
          - '/nexus*'
      backends:
        - serviceName: nexus
          servicePort: 8081