image:
    nfs:
        repository: quay.io/k8scsi/nfsplugin
        tag: v2.0.0
        pullPolicy:   IfNotPresent
    csiProvisioner:
        repository: registry.k8s.io/sig-storage/csi-provisioner
        tag: v2.0.4
        pullPolicy: IfNotPresent
    livenessProbe:
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: v2.1.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.0.1
        pullPolicy: IfNotPresent
serviceAccount:
  create: true
rbac:
  create: true
controller:
  replicas: 2
