# myservice.yaml
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector: # Pod Label 的标签选择器
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: myapp-http